import type { ClientErrorKind } from './api-client.js';

export const strings = {
  title: '视觉提示词编译器',
  edition: '校样台 · M4',
  description: '把模糊需求整理成三份可检查、可修改的视觉方向。',
  nav: {
    newDraft: '新建',
    history: '历史',
    favorites: '收藏',
    settings: '设置',
  },
  form: {
    section: '01 / 简报',
    brief: '描述你想要的画面',
    briefPlaceholder:
      '例如：为城市夜跑活动设计一张竖版海报，潮湿街道，醒目的中文标题……',
    typeLegend: '任务类型',
    autoType: '自动判断',
    manualType: '手动指定',
    manualTypeLabel: '选择任务类型',
    aspectRatio: '画面比例',
    customRatio: '自定义比例',
    mandatoryText: '必须出现的文字',
    mandatoryTextHint: '每行一项；会逐字保留',
    mandatoryElements: '必须元素',
    forbiddenElements: '禁止元素',
    listHint: '每行一项',
    creativity: '创意自由度',
    advanced: '高级设置',
    allowAssumptions: '允许补充合理假设',
    outputLanguage: '输出语言',
    compile: '编译三份方向',
    compiling: '正在编译…',
    reset: '清空当前简报',
  },
  result: {
    section: '02 / 校样结果',
    normalized: '标准化简报',
    goal: '目标',
    deliverable: '交付物',
    detectedType: '任务类型',
    aspectRatio: '比例',
    specDetails: '展开视觉规格',
    subject: '主体',
    hierarchy: '视觉焦点',
    composition: '构图',
    lighting: '光线',
    palette: '色彩',
    materials: '材质',
    mandatoryText: '固定文字',
    mandatoryElements: '必须元素',
    forbiddenElements: '禁止元素',
    unspecified: '未指定',
    assumptions: '关键假设',
    risks: '风险与待确认项',
    noAssumptions: '未补充假设',
    noRisks: '未发现显式风险',
    needsInput: '这份简报仍有阻断问题，请补充后重试。',
    promptFull: '完整提示词',
    promptCompact: '精简提示词',
    differenceAxes: '差异轴',
    negative: '禁止项',
    copyFull: '复制完整提示词',
    copyCompact: '复制精简提示词',
    copied: '已复制',
    favorite: '收藏方向',
    unfavorite: '取消收藏',
    reviseLabel: '只修改这个方向',
    revisePlaceholder: '例如：保留构图，改为雨后清晨的冷暖光线',
    revise: '提交修改',
    revising: '正在修改…',
    score: '约束评分',
    modes: {
      faithful: '稳妥',
      creative: '创意',
      experimental: '实验',
    },
  },
  panels: {
    historyTitle: '最近历史',
    favoritesTitle: '收藏方向',
    settingsTitle: '设置',
    emptyHistory: '还没有编译记录。',
    emptyFavorites: '还没有收藏方向。',
    restore: '恢复这次结果',
    removeHistory: '清空历史',
    clearFavorites: '清空收藏',
    apiEndpoint: 'API 地址',
    apiEndpointHint: '由构建变量 VITE_API_BASE_URL 决定。',
    storageCounts: '本地容量',
    storageCountsValue: '历史最多 20 条，收藏最多 50 条。',
    localOnly: '只保存在 chrome.storage.local，不保存 API Key。',
  },
  status: {
    loading: '请求已发送，请稍候。',
    compileSuccess: '编译完成，已显示三份方向。',
    reviseSuccess: '方向修改完成，结果已更新。',
    restoreSuccess: '历史结果已恢复。',
    saved: '已保存到本地。',
    cleared: '本地记录已清空。',
    storageError: '本地存储操作失败。请检查扩展存储权限后重试。',
    copyError: '复制失败，请选择提示词后手动复制。',
    retry: '重试上一次请求',
    errorTitle: '本次请求未完成',
  },
  errors: {
    timeout: '服务响应超时，可以稍后重试。',
    offline: '无法连接本地 API。请确认服务已启动且地址可访问。',
    rate_limited: '请求过于频繁，请稍候再试。',
    invalid_output: '服务返回的数据未通过契约校验，结果没有被采用。',
    upstream: '上游服务暂时不可用，可以稍后重试。',
    invalid_request: '请求包含无效或冲突内容，请修改简报后重试。',
  } satisfies Record<ClientErrorKind, string>,
} as const;

export const taskTypeOptions = [
  ['poster', '海报'],
  ['photography', '摄影'],
  ['product_concept', '产品概念'],
  ['three_d_scene', '三维场景'],
  ['infographic', '信息图'],
  ['character_design', '角色设计'],
  ['image_edit', '图片编辑'],
  ['storyboard', '分镜'],
  ['general', '通用'],
] as const;

export const aspectRatioOptions = [
  ['auto', '自动'],
  ['1:1', '1:1 方形'],
  ['4:3', '4:3 横向'],
  ['3:4', '3:4 竖向'],
  ['16:9', '16:9 宽屏'],
  ['9:16', '9:16 竖屏'],
  ['custom', '自定义'],
] as const;
